name: Deploy para Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Instalar dependências (client)
        run: npm ci
        working-directory: client

      - name: Build do React
        run: npm run build
        working-directory: client

      - name: Instalar dependências (functions)
        run: npm ci
        working-directory: functions

      - name: Build das Firebase Functions
        run: npm run build
        working-directory: functions

      - name: Deploy Hosting para Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: formcraft-52279

